name: Release
on:
  push:
    branches:
      - main
env:
  DOCKER_REPO: desyco
jobs:
  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump_version.outputs.new_tag }}
      APP_NAME: ${{ steps.repository_name.outputs.value }}
    steps:
      - id: repository_name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
      - uses: actions/checkout@v2
#      TODO
#      - name: Bump version and push tag
#        id: bump_version
#        uses: hennejg/github-tag-action@v4.3.1
#        with:
#          tag_prefix: ''
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#      - run: echo "VERSION=${{ steps.bump_version.outputs.new_tag }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
      - name: Install yarn
        run: npm -g install yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - name: Build ui
        run: CI=false yarn run build
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver: docker
      - name: Logging to docker registry
        run: docker login -u desyco -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: build docker image
        run: docker build --tag desyco/vidbid-frontend:0.0.4 .
      - name: push docker image
        run: docker push desyco/vidbid-frontend:0.0.4